# Generated by Django 2.2.3 on 2019-07-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_auto_20190719_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director',
            new_name='Staff',
        ),
    ]
