# Generated by Django 2.2.3 on 2019-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0004_auto_20190722_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('student_count', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='additional_information',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='reason',
            field=models.TextField(max_length=1000),
        ),
    ]
