# Generated by Django 2.2.3 on 2019-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0005_auto_20190722_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_number',
            new_name='claim_title',
        ),
    ]
