# Generated by Django 2.2.3 on 2019-07-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0006_auto_20190722_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInsured',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecole.Student')),
            ],
            bases=('ecole.student',),
        ),
        migrations.RemoveField(
            model_name='student',
            name='insured',
        ),
        migrations.AlterField(
            model_name='school',
            name='student_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.DateField(),
        ),
    ]
