# Generated by Django 2.2.3 on 2019-07-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0007_auto_20190722_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInsured',
        ),
    ]
