# Generated by Django 2.2.3 on 2019-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0008_delete_studentinsured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.CharField(max_length=100),
        ),
    ]
