# Generated by Django 2.2.3 on 2019-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0009_auto_20190722_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.DateField(),
        ),
    ]
