# Generated by Django 2.2.3 on 2019-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0011_auto_20190725_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='assure',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
