# Generated by Django 2.2.3 on 2019-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0012_eleve_assure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='nom_directeur',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
